///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SyncSharepointFilesAndFolders
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SyncSharepointFilesAndFoldersRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("f06c2356-b1a3-444e-a614-1d55de7f783d")]
    public partial class SyncSharepointFilesAndFoldersRepository : RepoGenBaseFolder
    {
        static SyncSharepointFilesAndFoldersRepository instance = new SyncSharepointFilesAndFoldersRepository();
        SyncSharepointFilesAndFoldersRepositoryFolders.HarulaDocumentsAllDocumentsAppFolder _haruladocumentsalldocuments;
        SyncSharepointFilesAndFoldersRepositoryFolders.InternetExplorerAppFolder _internetexplorer;
        SyncSharepointFilesAndFoldersRepositoryFolders.MicrosoftOneDriveAppFolder _microsoftonedrive;
        SyncSharepointFilesAndFoldersRepositoryFolders.ExplorerAppFolder _explorer;
        SyncSharepointFilesAndFoldersRepositoryFolders.CUsersUserDocumentsRanorexRanorexSAppFolder _cusersuserdocumentsranorexranorexs;
        SyncSharepointFilesAndFoldersRepositoryFolders.Files2AppFolder _files2;
        SyncSharepointFilesAndFoldersRepositoryFolders.OneDriveAppFolder _onedrive;
        SyncSharepointFilesAndFoldersRepositoryFolders.Copy_of_CUsersUserDocumentsRanorexRanorexSAppFolder _copy_of_cusersuserdocumentsranorexranorexs;
        RepoItemInfo _copy_of_cancelInfo;

        /// <summary>
        /// Gets the singleton class instance representing the SyncSharepointFilesAndFoldersRepository element repository.
        /// </summary>
        [RepositoryFolder("f06c2356-b1a3-444e-a614-1d55de7f783d")]
        public static SyncSharepointFilesAndFoldersRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SyncSharepointFilesAndFoldersRepository() 
            : base("SyncSharepointFilesAndFoldersRepository", "/", null, 0, false, "f06c2356-b1a3-444e-a614-1d55de7f783d", ".\\RepositoryImages\\SyncSharepointFilesAndFoldersRepositoryf06c2356.rximgres")
        {
            _haruladocumentsalldocuments = new SyncSharepointFilesAndFoldersRepositoryFolders.HarulaDocumentsAllDocumentsAppFolder(this);
            _internetexplorer = new SyncSharepointFilesAndFoldersRepositoryFolders.InternetExplorerAppFolder(this);
            _microsoftonedrive = new SyncSharepointFilesAndFoldersRepositoryFolders.MicrosoftOneDriveAppFolder(this);
            _explorer = new SyncSharepointFilesAndFoldersRepositoryFolders.ExplorerAppFolder(this);
            _cusersuserdocumentsranorexranorexs = new SyncSharepointFilesAndFoldersRepositoryFolders.CUsersUserDocumentsRanorexRanorexSAppFolder(this);
            _files2 = new SyncSharepointFilesAndFoldersRepositoryFolders.Files2AppFolder(this);
            _onedrive = new SyncSharepointFilesAndFoldersRepositoryFolders.OneDriveAppFolder(this);
            _copy_of_cusersuserdocumentsranorexranorexs = new SyncSharepointFilesAndFoldersRepositoryFolders.Copy_of_CUsersUserDocumentsRanorexRanorexSAppFolder(this);
            _copy_of_cancelInfo = new RepoItemInfo(this, "Copy_of_Cancel", "/form[@processname='OneDrive' and @instance='0']/button[1]", 30000, null, "d72752f5-0df9-4f6d-939a-20b209770648");
        }

#region Variables

        string _string2 = "Asia Q2 Sales.xlsx";

        /// <summary>
        /// Gets or sets the value of variable string2.
        /// </summary>
        [TestVariable("d36ad539-c7b6-4a5d-ac39-f676f319ba60")]
        public string string2
        {
            get { return _string2; }
            set { _string2 = value; }
        }

        string _string3 = "Carbon 3D Printing Proposal.docx";

        /// <summary>
        /// Gets or sets the value of variable string3.
        /// </summary>
        [TestVariable("3ccb3ac3-73ee-4f70-89e3-1c4a789d4618")]
        public string string3
        {
            get { return _string3; }
            set { _string3 = value; }
        }

        string _string4 = "Contoso Sales by Product Analysis.xlsx";

        /// <summary>
        /// Gets or sets the value of variable string4.
        /// </summary>
        [TestVariable("72489f8b-2ecd-4afa-a2f9-8127ecf0f18a")]
        public string string4
        {
            get { return _string4; }
            set { _string4 = value; }
        }

        string _string7 = "";

        /// <summary>
        /// Gets or sets the value of variable string7.
        /// </summary>
        [TestVariable("c6f7ae94-420b-4749-b246-b210c4824dcd")]
        public string string7
        {
            get { return _string7; }
            set { _string7 = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f06c2356-b1a3-444e-a614-1d55de7f783d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Copy_of_Cancel item.
        /// </summary>
        [RepositoryItem("d72752f5-0df9-4f6d-939a-20b209770648")]
        public virtual Ranorex.Button Copy_of_Cancel
        {
            get
            {
                 return _copy_of_cancelInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Copy_of_Cancel item info.
        /// </summary>
        [RepositoryItemInfo("d72752f5-0df9-4f6d-939a-20b209770648")]
        public virtual RepoItemInfo Copy_of_CancelInfo
        {
            get
            {
                return _copy_of_cancelInfo;
            }
        }

        /// <summary>
        /// The HarulaDocumentsAllDocuments folder.
        /// </summary>
        [RepositoryFolder("a98e4abc-5461-4a4b-900f-768f0f55bef0")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.HarulaDocumentsAllDocumentsAppFolder HarulaDocumentsAllDocuments
        {
            get { return _haruladocumentsalldocuments; }
        }

        /// <summary>
        /// The InternetExplorer folder.
        /// </summary>
        [RepositoryFolder("bdbeea7b-cbe0-4fef-a228-9f8b179e7587")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.InternetExplorerAppFolder InternetExplorer
        {
            get { return _internetexplorer; }
        }

        /// <summary>
        /// The MicrosoftOneDrive folder.
        /// </summary>
        [RepositoryFolder("d49c0d23-03b6-482b-b609-04c6c8b17ef9")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.MicrosoftOneDriveAppFolder MicrosoftOneDrive
        {
            get { return _microsoftonedrive; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("622450e6-5b09-491c-a9f0-bf1193403d0f")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The CUsersUserDocumentsRanorexRanorexS folder.
        /// </summary>
        [RepositoryFolder("b8b8f1a6-8a9b-4949-a305-7391f75392de")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.CUsersUserDocumentsRanorexRanorexSAppFolder CUsersUserDocumentsRanorexRanorexS
        {
            get { return _cusersuserdocumentsranorexranorexs; }
        }

        /// <summary>
        /// The Files2 folder.
        /// </summary>
        [RepositoryFolder("64e8711a-1757-4b13-a989-c81cd9ab9f52")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.Files2AppFolder Files2
        {
            get { return _files2; }
        }

        /// <summary>
        /// The OneDrive folder.
        /// </summary>
        [RepositoryFolder("feb7af36-a00f-40a9-b583-fe174e1ad4b8")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.OneDriveAppFolder OneDrive
        {
            get { return _onedrive; }
        }

        /// <summary>
        /// The Copy_of_CUsersUserDocumentsRanorexRanorexS folder.
        /// </summary>
        [RepositoryFolder("a4db7f00-04cc-447f-a024-3e71b7c1fddf")]
        public virtual SyncSharepointFilesAndFoldersRepositoryFolders.Copy_of_CUsersUserDocumentsRanorexRanorexSAppFolder Copy_of_CUsersUserDocumentsRanorexRanorexS
        {
            get { return _copy_of_cusersuserdocumentsranorexranorexs; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class SyncSharepointFilesAndFoldersRepositoryFolders
    {
        /// <summary>
        /// The HarulaDocumentsAllDocumentsAppFolder folder.
        /// </summary>
        [RepositoryFolder("a98e4abc-5461-4a4b-900f-768f0f55bef0")]
        public partial class HarulaDocumentsAllDocumentsAppFolder : RepoGenBaseFolder
        {
            SyncSharepointFilesAndFoldersRepositoryFolders.OdOverlayHostContentFolder _odoverlayhostcontent;
            RepoItemInfo _syncInfo;
            RepoItemInfo _credpasswordinputtextInfo;
            RepoItemInfo _credsigninbuttonInfo;
            RepoItemInfo _fileInfo;
            RepoItemInfo _divtaguseaInfo;
            RepoItemInfo _creduseridinputtextInfo;
            RepoItemInfo _delete1Info;

            /// <summary>
            /// Creates a new HarulaDocumentsAllDocuments  folder.
            /// </summary>
            public HarulaDocumentsAllDocumentsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HarulaDocumentsAllDocuments", "/dom", parentFolder, 30000, null, false, "a98e4abc-5461-4a4b-900f-768f0f55bef0", "")
            {
                _odoverlayhostcontent = new SyncSharepointFilesAndFoldersRepositoryFolders.OdOverlayHostContentFolder(this);
                _syncInfo = new RepoItemInfo(this, "Sync", ".//div[#'appRoot']/div/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div/div[2]/div[4]/div/?/?/span[2]", 30000, null, "17757aba-2534-4e9f-8fb4-0472a239f8f0");
                _credpasswordinputtextInfo = new RepoItemInfo(this, "CredPasswordInputtext", ".//input[#'cred_password_inputtext']", 30000, null, "6e163dd9-e18e-4750-a57e-cf0da386ed76");
                _credsigninbuttonInfo = new RepoItemInfo(this, "CredSignInButton", ".//button[#'cred_sign_in_button']", 30000, null, "a93b2823-704c-4663-8ccf-c7d857c9b1f1");
                _fileInfo = new RepoItemInfo(this, "File", ".//div[#'appRoot']/div/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div/div[2]/div[2]/div/?/?/input", 30000, null, "ff9e9963-ea25-4966-8f12-9054743d7570");
                _divtaguseaInfo = new RepoItemInfo(this, "DivTagUseA", ".//table[#'use_another_account']//td/table/tbody/tr[2]/td[2]/div[1]", 30000, null, "93968960-9963-48cc-b538-5b6c1604fbcc");
                _creduseridinputtextInfo = new RepoItemInfo(this, "CredUseridInputtext", ".//input[#'cred_userid_inputtext']", 30000, null, "9c4ccc8b-272b-4377-ad50-1df41f952c27");
                _delete1Info = new RepoItemInfo(this, "Delete1", ".//div[#'appRoot']/div/div[6]/div/div/div/div/div[2]/div/div/div[2]/div[2]//button[1]/span[2]", 30000, null, "26e97ace-bd2f-4bee-884b-776144cc19a7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a98e4abc-5461-4a4b-900f-768f0f55bef0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a98e4abc-5461-4a4b-900f-768f0f55bef0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Sync item.
            /// </summary>
            [RepositoryItem("17757aba-2534-4e9f-8fb4-0472a239f8f0")]
            public virtual Ranorex.SpanTag Sync
            {
                get
                {
                    return _syncInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Sync item info.
            /// </summary>
            [RepositoryItemInfo("17757aba-2534-4e9f-8fb4-0472a239f8f0")]
            public virtual RepoItemInfo SyncInfo
            {
                get
                {
                    return _syncInfo;
                }
            }

            /// <summary>
            /// The CredPasswordInputtext item.
            /// </summary>
            [RepositoryItem("6e163dd9-e18e-4750-a57e-cf0da386ed76")]
            public virtual Ranorex.InputTag CredPasswordInputtext
            {
                get
                {
                    return _credpasswordinputtextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CredPasswordInputtext item info.
            /// </summary>
            [RepositoryItemInfo("6e163dd9-e18e-4750-a57e-cf0da386ed76")]
            public virtual RepoItemInfo CredPasswordInputtextInfo
            {
                get
                {
                    return _credpasswordinputtextInfo;
                }
            }

            /// <summary>
            /// The CredSignInButton item.
            /// </summary>
            [RepositoryItem("a93b2823-704c-4663-8ccf-c7d857c9b1f1")]
            public virtual Ranorex.ButtonTag CredSignInButton
            {
                get
                {
                    return _credsigninbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The CredSignInButton item info.
            /// </summary>
            [RepositoryItemInfo("a93b2823-704c-4663-8ccf-c7d857c9b1f1")]
            public virtual RepoItemInfo CredSignInButtonInfo
            {
                get
                {
                    return _credsigninbuttonInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("ff9e9963-ea25-4966-8f12-9054743d7570")]
            public virtual Ranorex.InputTag File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("ff9e9963-ea25-4966-8f12-9054743d7570")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The DivTagUseA item.
            /// </summary>
            [RepositoryItem("93968960-9963-48cc-b538-5b6c1604fbcc")]
            public virtual Ranorex.DivTag DivTagUseA
            {
                get
                {
                    return _divtaguseaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagUseA item info.
            /// </summary>
            [RepositoryItemInfo("93968960-9963-48cc-b538-5b6c1604fbcc")]
            public virtual RepoItemInfo DivTagUseAInfo
            {
                get
                {
                    return _divtaguseaInfo;
                }
            }

            /// <summary>
            /// The CredUseridInputtext item.
            /// </summary>
            [RepositoryItem("9c4ccc8b-272b-4377-ad50-1df41f952c27")]
            public virtual Ranorex.InputTag CredUseridInputtext
            {
                get
                {
                    return _creduseridinputtextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CredUseridInputtext item info.
            /// </summary>
            [RepositoryItemInfo("9c4ccc8b-272b-4377-ad50-1df41f952c27")]
            public virtual RepoItemInfo CredUseridInputtextInfo
            {
                get
                {
                    return _creduseridinputtextInfo;
                }
            }

            /// <summary>
            /// The Delete1 item.
            /// </summary>
            [RepositoryItem("26e97ace-bd2f-4bee-884b-776144cc19a7")]
            public virtual Ranorex.SpanTag Delete1
            {
                get
                {
                    return _delete1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Delete1 item info.
            /// </summary>
            [RepositoryItemInfo("26e97ace-bd2f-4bee-884b-776144cc19a7")]
            public virtual RepoItemInfo Delete1Info
            {
                get
                {
                    return _delete1Info;
                }
            }

            /// <summary>
            /// The OdOverlayHostContent folder.
            /// </summary>
            [RepositoryFolder("52d56af2-9910-4931-b83d-b82bd2a6a1ce")]
            public virtual SyncSharepointFilesAndFoldersRepositoryFolders.OdOverlayHostContentFolder OdOverlayHostContent
            {
                get { return _odoverlayhostcontent; }
            }
        }

        /// <summary>
        /// The OdOverlayHostContentFolder folder.
        /// </summary>
        [RepositoryFolder("52d56af2-9910-4931-b83d-b82bd2a6a1ce")]
        public partial class OdOverlayHostContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _deleteInfo;
            RepoItemInfo _someitagInfo;
            RepoItemInfo _someitag1Info;
            RepoItemInfo _someitag2Info;

            /// <summary>
            /// Creates a new OdOverlayHostContent  folder.
            /// </summary>
            public OdOverlayHostContentFolder(RepoGenBaseFolder parentFolder) :
                    base("OdOverlayHostContent", ".//div[#'appRoot']/div/div[3]/div/div[2]/div[3]", parentFolder, 30000, null, false, "52d56af2-9910-4931-b83d-b82bd2a6a1ce", "")
            {
                _deleteInfo = new RepoItemInfo(this, "Delete", "div[1]/div/div[3]/div/div[2]/div[2]//span[2]", 30000, null, "b77e5a11-3b1c-4077-848b-2a5a45497d8a");
                _someitagInfo = new RepoItemInfo(this, "SomeITag", "div[2]/div[1]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[1]/div/div/div[1]/?/?/div", 30000, null, "7d5b5188-ac54-48cf-b4e5-6f5e5518fd05");
                _someitag1Info = new RepoItemInfo(this, "SomeITag1", "div[2]/div[1]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[1]/?/?/div", 30000, null, "887adcfa-7368-41a3-976f-d578f859a07e");
                _someitag2Info = new RepoItemInfo(this, "SomeITag2", "div[2]/div[1]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div[1]/?/?/div", 30000, null, "c9faa392-cc99-4af8-bc1b-438fed34ef51");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("52d56af2-9910-4931-b83d-b82bd2a6a1ce")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("52d56af2-9910-4931-b83d-b82bd2a6a1ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("b77e5a11-3b1c-4077-848b-2a5a45497d8a")]
            public virtual Ranorex.SpanTag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("b77e5a11-3b1c-4077-848b-2a5a45497d8a")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The SomeITag item.
            /// </summary>
            [RepositoryItem("7d5b5188-ac54-48cf-b4e5-6f5e5518fd05")]
            public virtual Ranorex.DivTag SomeITag
            {
                get
                {
                    return _someitagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeITag item info.
            /// </summary>
            [RepositoryItemInfo("7d5b5188-ac54-48cf-b4e5-6f5e5518fd05")]
            public virtual RepoItemInfo SomeITagInfo
            {
                get
                {
                    return _someitagInfo;
                }
            }

            /// <summary>
            /// The SomeITag1 item.
            /// </summary>
            [RepositoryItem("887adcfa-7368-41a3-976f-d578f859a07e")]
            public virtual Ranorex.DivTag SomeITag1
            {
                get
                {
                    return _someitag1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeITag1 item info.
            /// </summary>
            [RepositoryItemInfo("887adcfa-7368-41a3-976f-d578f859a07e")]
            public virtual RepoItemInfo SomeITag1Info
            {
                get
                {
                    return _someitag1Info;
                }
            }

            /// <summary>
            /// The SomeITag2 item.
            /// </summary>
            [RepositoryItem("c9faa392-cc99-4af8-bc1b-438fed34ef51")]
            public virtual Ranorex.DivTag SomeITag2
            {
                get
                {
                    return _someitag2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeITag2 item info.
            /// </summary>
            [RepositoryItemInfo("c9faa392-cc99-4af8-bc1b-438fed34ef51")]
            public virtual RepoItemInfo SomeITag2Info
            {
                get
                {
                    return _someitag2Info;
                }
            }
        }

        /// <summary>
        /// The InternetExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("bdbeea7b-cbe0-4fef-a228-9f8b179e7587")]
        public partial class InternetExplorerAppFolder : RepoGenBaseFolder
        {
            SyncSharepointFilesAndFoldersRepositoryFolders.ShellViewFolder _shellview;
            RepoItemInfo _buttonallowInfo;
            RepoItemInfo _toolbar1001Info;

            /// <summary>
            /// Creates a new InternetExplorer  folder.
            /// </summary>
            public InternetExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InternetExplorer", "/form[@processname='iexplore' and @accessiblerole='Dialog']", parentFolder, 30000, null, true, "bdbeea7b-cbe0-4fef-a228-9f8b179e7587", "")
            {
                _shellview = new SyncSharepointFilesAndFoldersRepositoryFolders.ShellViewFolder(this);
                _buttonallowInfo = new RepoItemInfo(this, "ButtonAllow", "button[1]", 30000, null, "e3cfb83a-9312-467b-b978-8cb039a97bc6");
                _toolbar1001Info = new RepoItemInfo(this, "ToolBar1001", "element[@class='WorkerW']/?/?/element[@controlid='41477']//toolbar[@controlid='1001']", 30000, null, "1c071185-d9fb-44b5-91ff-ec2386f094a4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bdbeea7b-cbe0-4fef-a228-9f8b179e7587")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bdbeea7b-cbe0-4fef-a228-9f8b179e7587")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonAllow item.
            /// </summary>
            [RepositoryItem("e3cfb83a-9312-467b-b978-8cb039a97bc6")]
            public virtual Ranorex.Button ButtonAllow
            {
                get
                {
                    return _buttonallowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAllow item info.
            /// </summary>
            [RepositoryItemInfo("e3cfb83a-9312-467b-b978-8cb039a97bc6")]
            public virtual RepoItemInfo ButtonAllowInfo
            {
                get
                {
                    return _buttonallowInfo;
                }
            }

            /// <summary>
            /// The ToolBar1001 item.
            /// </summary>
            [RepositoryItem("1c071185-d9fb-44b5-91ff-ec2386f094a4")]
            public virtual Ranorex.ToolBar ToolBar1001
            {
                get
                {
                    return _toolbar1001Info.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The ToolBar1001 item info.
            /// </summary>
            [RepositoryItemInfo("1c071185-d9fb-44b5-91ff-ec2386f094a4")]
            public virtual RepoItemInfo ToolBar1001Info
            {
                get
                {
                    return _toolbar1001Info;
                }
            }

            /// <summary>
            /// The ShellView folder.
            /// </summary>
            [RepositoryFolder("a9a144d9-c4c3-467f-8bd4-c9f82c264290")]
            public virtual SyncSharepointFilesAndFoldersRepositoryFolders.ShellViewFolder ShellView
            {
                get { return _shellview; }
            }
        }

        /// <summary>
        /// The ShellViewFolder folder.
        /// </summary>
        [RepositoryFolder("a9a144d9-c4c3-467f-8bd4-c9f82c264290")]
        public partial class ShellViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _systemitemnamedisplay1Info;
            RepoItemInfo _systemitemnamedisplay2Info;

            /// <summary>
            /// Creates a new ShellView  folder.
            /// </summary>
            public ShellViewFolder(RepoGenBaseFolder parentFolder) :
                    base("ShellView", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']", parentFolder, 30000, null, false, "a9a144d9-c4c3-467f-8bd4-c9f82c264290", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "?/?/listitem/text[@uiautomationvaluevalue=$string2]", 30000, null, "937c5cf3-3dea-4dd5-9005-919703929ae3");
                _systemitemnamedisplay1Info = new RepoItemInfo(this, "SystemItemNameDisplay1", "?/?/listitem/text[@uiautomationvaluevalue=$string3]", 30000, null, "29160b85-5a9d-4400-81ba-95028418931d");
                _systemitemnamedisplay2Info = new RepoItemInfo(this, "SystemItemNameDisplay2", "?/?/listitem/text[@uiautomationvaluevalue=$string4]", 30000, null, "ac584086-3b51-410d-8646-9a050ec8f3b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a9a144d9-c4c3-467f-8bd4-c9f82c264290")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a9a144d9-c4c3-467f-8bd4-c9f82c264290")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("937c5cf3-3dea-4dd5-9005-919703929ae3")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("937c5cf3-3dea-4dd5-9005-919703929ae3")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item.
            /// </summary>
            [RepositoryItem("29160b85-5a9d-4400-81ba-95028418931d")]
            public virtual Ranorex.Text SystemItemNameDisplay1
            {
                get
                {
                    return _systemitemnamedisplay1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item info.
            /// </summary>
            [RepositoryItemInfo("29160b85-5a9d-4400-81ba-95028418931d")]
            public virtual RepoItemInfo SystemItemNameDisplay1Info
            {
                get
                {
                    return _systemitemnamedisplay1Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay2 item.
            /// </summary>
            [RepositoryItem("ac584086-3b51-410d-8646-9a050ec8f3b3")]
            public virtual Ranorex.Text SystemItemNameDisplay2
            {
                get
                {
                    return _systemitemnamedisplay2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay2 item info.
            /// </summary>
            [RepositoryItemInfo("ac584086-3b51-410d-8646-9a050ec8f3b3")]
            public virtual RepoItemInfo SystemItemNameDisplay2Info
            {
                get
                {
                    return _systemitemnamedisplay2Info;
                }
            }
        }

        /// <summary>
        /// The MicrosoftOneDriveAppFolder folder.
        /// </summary>
        [RepositoryFolder("d49c0d23-03b6-482b-b609-04c6c8b17ef9")]
        public partial class MicrosoftOneDriveAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text8512Info;
            RepoItemInfo _signinInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _settingsInfo;
            RepoItemInfo _text8050Info;

            /// <summary>
            /// Creates a new MicrosoftOneDrive  folder.
            /// </summary>
            public MicrosoftOneDriveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftOneDrive", "/form[@processname='OneDrive' and @accessiblerole='Dialog']", parentFolder, 30000, null, true, "d49c0d23-03b6-482b-b609-04c6c8b17ef9", "")
            {
                _text8512Info = new RepoItemInfo(this, "Text8512", "?/?/text[@controlid='8512']", 30000, null, "6b8051e4-a39b-4c7a-b022-a3ccfb294675");
                _signinInfo = new RepoItemInfo(this, "SignIn", "container/button[1]", 30000, null, "30f14fc6-05a8-45c7-b4e3-e6963a91782e");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/titlebar/button[3]", 30000, null, "e9ca4d4e-b029-409b-917f-14cdab9d27ff");
                _settingsInfo = new RepoItemInfo(this, "Settings", "?/?/tabpage[1]", 30000, null, "1bf1383d-5151-4a55-935e-eb4a5273656a");
                _text8050Info = new RepoItemInfo(this, "Text8050", "container/element[@controlid='8034']/element/element[2]/text[@controlid='8050']", 30000, null, "3ac0b1fb-db8f-471f-a362-111bf029a887");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d49c0d23-03b6-482b-b609-04c6c8b17ef9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d49c0d23-03b6-482b-b609-04c6c8b17ef9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text8512 item.
            /// </summary>
            [RepositoryItem("6b8051e4-a39b-4c7a-b022-a3ccfb294675")]
            public virtual Ranorex.Text Text8512
            {
                get
                {
                    return _text8512Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text8512 item info.
            /// </summary>
            [RepositoryItemInfo("6b8051e4-a39b-4c7a-b022-a3ccfb294675")]
            public virtual RepoItemInfo Text8512Info
            {
                get
                {
                    return _text8512Info;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("30f14fc6-05a8-45c7-b4e3-e6963a91782e")]
            public virtual Ranorex.Button SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("30f14fc6-05a8-45c7-b4e3-e6963a91782e")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("e9ca4d4e-b029-409b-917f-14cdab9d27ff")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("e9ca4d4e-b029-409b-917f-14cdab9d27ff")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Settings item.
            /// </summary>
            [RepositoryItem("1bf1383d-5151-4a55-935e-eb4a5273656a")]
            public virtual Ranorex.TabPage Settings
            {
                get
                {
                    return _settingsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Settings item info.
            /// </summary>
            [RepositoryItemInfo("1bf1383d-5151-4a55-935e-eb4a5273656a")]
            public virtual RepoItemInfo SettingsInfo
            {
                get
                {
                    return _settingsInfo;
                }
            }

            /// <summary>
            /// The Text8050 item.
            /// </summary>
            [RepositoryItem("3ac0b1fb-db8f-471f-a362-111bf029a887")]
            public virtual Ranorex.Text Text8050
            {
                get
                {
                    return _text8050Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text8050 item info.
            /// </summary>
            [RepositoryItemInfo("3ac0b1fb-db8f-471f-a362-111bf029a887")]
            public virtual RepoItemInfo Text8050Info
            {
                get
                {
                    return _text8050Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("622450e6-5b09-491c-a9f0-bf1193403d0f")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _internetexplorer1runningwindowInfo;
            RepoItemInfo _fileexplorer1runningwindowInfo;
            RepoItemInfo _showdesktopInfo;
            RepoItemInfo _onedrivemoraviauptodateInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "622450e6-5b09-491c-a9f0-bf1193403d0f", "")
            {
                _internetexplorer1runningwindowInfo = new RepoItemInfo(this, "InternetExplorer1RunningWindow", "container//toolbar/button[@accessiblename~'Internet Explorer']", 30000, null, "3fb0c363-ad4e-43d8-81d5-9daec354090d");
                _fileexplorer1runningwindowInfo = new RepoItemInfo(this, "FileExplorer1RunningWindow", "container[@controlid='40965']//toolbar/button[1]", 30000, null, "403a3afe-abb2-4267-9718-8ef30d12c1b6");
                _showdesktopInfo = new RepoItemInfo(this, "ShowDesktop", "container[@controlid='303']/element[@controlid='307']", 30000, null, "233b8061-fb32-4b74-935d-f1f6be73251a");
                _onedrivemoraviauptodateInfo = new RepoItemInfo(this, "OneDriveMoraviaUpToDate", "?/?/container[@class='SysPager']/toolbar[@controlid='1504']/button[@text~'OneDrive - Moravia']", 30000, null, "1bc85667-29c9-4c0f-ac37-15a9f2448837");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("622450e6-5b09-491c-a9f0-bf1193403d0f")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("622450e6-5b09-491c-a9f0-bf1193403d0f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InternetExplorer1RunningWindow item.
            /// </summary>
            [RepositoryItem("3fb0c363-ad4e-43d8-81d5-9daec354090d")]
            public virtual Ranorex.Button InternetExplorer1RunningWindow
            {
                get
                {
                    return _internetexplorer1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The InternetExplorer1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("3fb0c363-ad4e-43d8-81d5-9daec354090d")]
            public virtual RepoItemInfo InternetExplorer1RunningWindowInfo
            {
                get
                {
                    return _internetexplorer1runningwindowInfo;
                }
            }

            /// <summary>
            /// The FileExplorer1RunningWindow item.
            /// </summary>
            [RepositoryItem("403a3afe-abb2-4267-9718-8ef30d12c1b6")]
            public virtual Ranorex.Button FileExplorer1RunningWindow
            {
                get
                {
                    return _fileexplorer1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FileExplorer1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("403a3afe-abb2-4267-9718-8ef30d12c1b6")]
            public virtual RepoItemInfo FileExplorer1RunningWindowInfo
            {
                get
                {
                    return _fileexplorer1runningwindowInfo;
                }
            }

            /// <summary>
            /// The ShowDesktop item.
            /// </summary>
            [RepositoryItem("233b8061-fb32-4b74-935d-f1f6be73251a")]
            public virtual Ranorex.Unknown ShowDesktop
            {
                get
                {
                    return _showdesktopInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ShowDesktop item info.
            /// </summary>
            [RepositoryItemInfo("233b8061-fb32-4b74-935d-f1f6be73251a")]
            public virtual RepoItemInfo ShowDesktopInfo
            {
                get
                {
                    return _showdesktopInfo;
                }
            }

            /// <summary>
            /// The OneDriveMoraviaUpToDate item.
            /// </summary>
            [RepositoryItem("1bc85667-29c9-4c0f-ac37-15a9f2448837")]
            public virtual Ranorex.Button OneDriveMoraviaUpToDate
            {
                get
                {
                    return _onedrivemoraviauptodateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OneDriveMoraviaUpToDate item info.
            /// </summary>
            [RepositoryItemInfo("1bc85667-29c9-4c0f-ac37-15a9f2448837")]
            public virtual RepoItemInfo OneDriveMoraviaUpToDateInfo
            {
                get
                {
                    return _onedrivemoraviauptodateInfo;
                }
            }
        }

        /// <summary>
        /// The CUsersUserDocumentsRanorexRanorexSAppFolder folder.
        /// </summary>
        [RepositoryFolder("b8b8f1a6-8a9b-4949-a305-7391f75392de")]
        public partial class CUsersUserDocumentsRanorexRanorexSAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _quickaccessInfo;
            RepoItemInfo _moraviaInfo;
            RepoItemInfo _haruladocumentsInfo;
            RepoItemInfo _copy_of_haruladocumentsInfo;

            /// <summary>
            /// Creates a new CUsersUserDocumentsRanorexRanorexS  folder.
            /// </summary>
            public CUsersUserDocumentsRanorexRanorexSAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CUsersUserDocumentsRanorexRanorexS", "/form[@processname='explorer']", parentFolder, 30000, null, true, "b8b8f1a6-8a9b-4949-a305-7391f75392de", "")
            {
                _quickaccessInfo = new RepoItemInfo(this, "QuickAccess", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element/element/tree/treeitem[1]", 30000, null, "6ec1353b-454e-4a37-90ef-03ae299eb696");
                _moraviaInfo = new RepoItemInfo(this, "Moravia", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[4]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Moravia']", 30000, null, "04054811-656b-4ba6-bb06-5dcda0122da8");
                _haruladocumentsInfo = new RepoItemInfo(this, "HarulaDocuments", "container//treeitem[@name~'harula']", 30000, null, "28a7c873-14c5-4cd6-a072-368b0786e55b");
                _copy_of_haruladocumentsInfo = new RepoItemInfo(this, "Copy_of_HarulaDocuments", "element[@class='ShellTabWindowClass']//element[@instance='1']/container/list", 30000, null, "111fac65-9d75-49a5-ad4e-9feb65edcb9e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b8b8f1a6-8a9b-4949-a305-7391f75392de")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8b8f1a6-8a9b-4949-a305-7391f75392de")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QuickAccess item.
            /// </summary>
            [RepositoryItem("6ec1353b-454e-4a37-90ef-03ae299eb696")]
            public virtual Ranorex.TreeItem QuickAccess
            {
                get
                {
                    return _quickaccessInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The QuickAccess item info.
            /// </summary>
            [RepositoryItemInfo("6ec1353b-454e-4a37-90ef-03ae299eb696")]
            public virtual RepoItemInfo QuickAccessInfo
            {
                get
                {
                    return _quickaccessInfo;
                }
            }

            /// <summary>
            /// The Moravia item.
            /// </summary>
            [RepositoryItem("04054811-656b-4ba6-bb06-5dcda0122da8")]
            public virtual Ranorex.TreeItem Moravia
            {
                get
                {
                    return _moraviaInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Moravia item info.
            /// </summary>
            [RepositoryItemInfo("04054811-656b-4ba6-bb06-5dcda0122da8")]
            public virtual RepoItemInfo MoraviaInfo
            {
                get
                {
                    return _moraviaInfo;
                }
            }

            /// <summary>
            /// The HarulaDocuments item.
            /// </summary>
            [RepositoryItem("28a7c873-14c5-4cd6-a072-368b0786e55b")]
            public virtual Ranorex.TreeItem HarulaDocuments
            {
                get
                {
                    return _haruladocumentsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The HarulaDocuments item info.
            /// </summary>
            [RepositoryItemInfo("28a7c873-14c5-4cd6-a072-368b0786e55b")]
            public virtual RepoItemInfo HarulaDocumentsInfo
            {
                get
                {
                    return _haruladocumentsInfo;
                }
            }

            /// <summary>
            /// The Copy_of_HarulaDocuments item.
            /// </summary>
            [RepositoryItem("111fac65-9d75-49a5-ad4e-9feb65edcb9e")]
            public virtual Ranorex.List Copy_of_HarulaDocuments
            {
                get
                {
                    return _copy_of_haruladocumentsInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Copy_of_HarulaDocuments item info.
            /// </summary>
            [RepositoryItemInfo("111fac65-9d75-49a5-ad4e-9feb65edcb9e")]
            public virtual RepoItemInfo Copy_of_HarulaDocumentsInfo
            {
                get
                {
                    return _copy_of_haruladocumentsInfo;
                }
            }
        }

        /// <summary>
        /// The Files2AppFolder folder.
        /// </summary>
        [RepositoryFolder("64e8711a-1757-4b13-a989-c81cd9ab9f52")]
        public partial class Files2AppFolder : RepoGenBaseFolder
        {
            SyncSharepointFilesAndFoldersRepositoryFolders.ShellViewFolder1 _shellview;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _vistaelementosInfo;
            RepoItemInfo _systemitemnamedisplay1Info;
            RepoItemInfo _systemitemnamedisplay2Info;

            /// <summary>
            /// Creates a new Files2  folder.
            /// </summary>
            public Files2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Files2", "/form[@processname='explorer' and @windowtext~'Files2']", parentFolder, 30000, null, true, "64e8711a-1757-4b13-a989-c81cd9ab9f52", "")
            {
                _shellview = new SyncSharepointFilesAndFoldersRepositoryFolders.ShellViewFolder1(this);
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='ShellTabWindowClass']//container[@automationid='FolderLayoutContainer']/?/?/list/listitem[@automationid='0']", 30000, null, "4bac66de-3820-48ae-be99-1399a0dc7e98");
                _vistaelementosInfo = new RepoItemInfo(this, "VistaElementos", "element[@class='ShellTabWindowClass']//element/container/list", 30000, null, "c8ee505a-e0e0-492c-a320-01dd70d67870");
                _systemitemnamedisplay1Info = new RepoItemInfo(this, "SystemItemNameDisplay1", "element[@class='ShellTabWindowClass']//element[@instance='1']//listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "db5301e9-8702-46d0-a1ae-5689d93e1f78");
                _systemitemnamedisplay2Info = new RepoItemInfo(this, "SystemItemNameDisplay2", "element[@class='ShellTabWindowClass']//element[@instance='1']//listitem[@automationid='4']/text[@automationid='System.ItemNameDisplay']", 30000, null, "d58d3428-9ae7-4acf-8488-1747e27e5ad5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("64e8711a-1757-4b13-a989-c81cd9ab9f52")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("64e8711a-1757-4b13-a989-c81cd9ab9f52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("4bac66de-3820-48ae-be99-1399a0dc7e98")]
            public virtual Ranorex.ListItem SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("4bac66de-3820-48ae-be99-1399a0dc7e98")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The VistaElementos item.
            /// </summary>
            [RepositoryItem("c8ee505a-e0e0-492c-a320-01dd70d67870")]
            public virtual Ranorex.List VistaElementos
            {
                get
                {
                    return _vistaelementosInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The VistaElementos item info.
            /// </summary>
            [RepositoryItemInfo("c8ee505a-e0e0-492c-a320-01dd70d67870")]
            public virtual RepoItemInfo VistaElementosInfo
            {
                get
                {
                    return _vistaelementosInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item.
            /// </summary>
            [RepositoryItem("db5301e9-8702-46d0-a1ae-5689d93e1f78")]
            public virtual Ranorex.Text SystemItemNameDisplay1
            {
                get
                {
                    return _systemitemnamedisplay1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item info.
            /// </summary>
            [RepositoryItemInfo("db5301e9-8702-46d0-a1ae-5689d93e1f78")]
            public virtual RepoItemInfo SystemItemNameDisplay1Info
            {
                get
                {
                    return _systemitemnamedisplay1Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay2 item.
            /// </summary>
            [RepositoryItem("d58d3428-9ae7-4acf-8488-1747e27e5ad5")]
            public virtual Ranorex.Text SystemItemNameDisplay2
            {
                get
                {
                    return _systemitemnamedisplay2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay2 item info.
            /// </summary>
            [RepositoryItemInfo("d58d3428-9ae7-4acf-8488-1747e27e5ad5")]
            public virtual RepoItemInfo SystemItemNameDisplay2Info
            {
                get
                {
                    return _systemitemnamedisplay2Info;
                }
            }

            /// <summary>
            /// The ShellView folder.
            /// </summary>
            [RepositoryFolder("9815f2ee-0930-43fa-b653-267649c154ca")]
            public virtual SyncSharepointFilesAndFoldersRepositoryFolders.ShellViewFolder1 ShellView
            {
                get { return _shellview; }
            }
        }

        /// <summary>
        /// The ShellViewFolder1 folder.
        /// </summary>
        [RepositoryFolder("9815f2ee-0930-43fa-b653-267649c154ca")]
        public partial class ShellViewFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _vistaelementos1Info;
            RepoItemInfo _listitem0Info;
            RepoItemInfo _listitem4Info;

            /// <summary>
            /// Creates a new ShellView  folder.
            /// </summary>
            public ShellViewFolder1(RepoGenBaseFolder parentFolder) :
                    base("ShellView", "element[@class='ShellTabWindowClass']//element[@instance='1']/container[@caption='ShellView']", parentFolder, 30000, null, false, "9815f2ee-0930-43fa-b653-267649c154ca", "")
            {
                _vistaelementos1Info = new RepoItemInfo(this, "VistaElementos1", "?/?/list[@accessiblename='Vista Elementos']", 30000, null, "b9ecb755-aea5-4b10-9563-9b4f858fe5b1");
                _listitem0Info = new RepoItemInfo(this, "ListItem0", "?/?/listitem[@automationid='0']", 30000, null, "808ee4e8-c1cc-4703-a9ae-6f6475f1e73b");
                _listitem4Info = new RepoItemInfo(this, "ListItem4", "?/?/listitem[@automationid='4']", 30000, null, "63d7b970-1f38-447a-9121-be06a131ba20");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9815f2ee-0930-43fa-b653-267649c154ca")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9815f2ee-0930-43fa-b653-267649c154ca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VistaElementos1 item.
            /// </summary>
            [RepositoryItem("b9ecb755-aea5-4b10-9563-9b4f858fe5b1")]
            public virtual Ranorex.List VistaElementos1
            {
                get
                {
                    return _vistaelementos1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The VistaElementos1 item info.
            /// </summary>
            [RepositoryItemInfo("b9ecb755-aea5-4b10-9563-9b4f858fe5b1")]
            public virtual RepoItemInfo VistaElementos1Info
            {
                get
                {
                    return _vistaelementos1Info;
                }
            }

            /// <summary>
            /// The ListItem0 item.
            /// </summary>
            [RepositoryItem("808ee4e8-c1cc-4703-a9ae-6f6475f1e73b")]
            public virtual Ranorex.ListItem ListItem0
            {
                get
                {
                    return _listitem0Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem0 item info.
            /// </summary>
            [RepositoryItemInfo("808ee4e8-c1cc-4703-a9ae-6f6475f1e73b")]
            public virtual RepoItemInfo ListItem0Info
            {
                get
                {
                    return _listitem0Info;
                }
            }

            /// <summary>
            /// The ListItem4 item.
            /// </summary>
            [RepositoryItem("63d7b970-1f38-447a-9121-be06a131ba20")]
            public virtual Ranorex.ListItem ListItem4
            {
                get
                {
                    return _listitem4Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem4 item info.
            /// </summary>
            [RepositoryItemInfo("63d7b970-1f38-447a-9121-be06a131ba20")]
            public virtual RepoItemInfo ListItem4Info
            {
                get
                {
                    return _listitem4Info;
                }
            }
        }

        /// <summary>
        /// The OneDriveAppFolder folder.
        /// </summary>
        [RepositoryFolder("feb7af36-a00f-40a9-b583-fe174e1ad4b8")]
        public partial class OneDriveAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _settingsInfo;

            /// <summary>
            /// Creates a new OneDrive  folder.
            /// </summary>
            public OneDriveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OneDrive", "/contextmenu[@processname='OneDrive']", parentFolder, 30000, null, false, "feb7af36-a00f-40a9-b583-fe174e1ad4b8", "")
            {
                _settingsInfo = new RepoItemInfo(this, "Settings", "?/?/menuitem[4]", 30000, null, "b9ab56b7-605f-4ba1-942d-3832f7755e00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("feb7af36-a00f-40a9-b583-fe174e1ad4b8")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("feb7af36-a00f-40a9-b583-fe174e1ad4b8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Settings item.
            /// </summary>
            [RepositoryItem("b9ab56b7-605f-4ba1-942d-3832f7755e00")]
            public virtual Ranorex.MenuItem Settings
            {
                get
                {
                    return _settingsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Settings item info.
            /// </summary>
            [RepositoryItemInfo("b9ab56b7-605f-4ba1-942d-3832f7755e00")]
            public virtual RepoItemInfo SettingsInfo
            {
                get
                {
                    return _settingsInfo;
                }
            }
        }

        /// <summary>
        /// The Copy_of_CUsersUserDocumentsRanorexRanorexSAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4db7f00-04cc-447f-a024-3e71b7c1fddf")]
        public partial class Copy_of_CUsersUserDocumentsRanorexRanorexSAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _copy_of_haruladocumentsInfo;

            /// <summary>
            /// Creates a new Copy_of_CUsersUserDocumentsRanorexRanorexS  folder.
            /// </summary>
            public Copy_of_CUsersUserDocumentsRanorexRanorexSAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Copy_of_CUsersUserDocumentsRanorexRanorexS", "/form[@processname='explorer' and @accessiblename~'harula']", parentFolder, 30000, null, true, "a4db7f00-04cc-447f-a024-3e71b7c1fddf", "")
            {
                _copy_of_haruladocumentsInfo = new RepoItemInfo(this, "Copy_of_HarulaDocuments", "element[@class='ShellTabWindowClass']//element[@instance='1']/container/list", 30000, null, "51b732eb-27a4-40a1-a8c8-960f5fb5564f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4db7f00-04cc-447f-a024-3e71b7c1fddf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4db7f00-04cc-447f-a024-3e71b7c1fddf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Copy_of_HarulaDocuments item.
            /// </summary>
            [RepositoryItem("51b732eb-27a4-40a1-a8c8-960f5fb5564f")]
            public virtual Ranorex.List Copy_of_HarulaDocuments
            {
                get
                {
                    return _copy_of_haruladocumentsInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Copy_of_HarulaDocuments item info.
            /// </summary>
            [RepositoryItemInfo("51b732eb-27a4-40a1-a8c8-960f5fb5564f")]
            public virtual RepoItemInfo Copy_of_HarulaDocumentsInfo
            {
                get
                {
                    return _copy_of_haruladocumentsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}