///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Odin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BillingModule recording.
    /// </summary>
    [TestModule("475d5862-6461-49f4-8a37-45f111e7f588", ModuleType.Recording, 1)]
    public partial class BillingModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OdinRepository repository.
        /// </summary>
        public static OdinRepository repo = OdinRepository.Instance;

        static BillingModule instance = new BillingModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BillingModule()
        {
            snapPath = "c:\\Users\\LMeskova\\Documents\\Ranorex\\RanorexStudio Projects\\Odin\\Odin\\_files\\Screens\\PTB\\";
            language = "en_US";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BillingModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _snapPath;

        /// <summary>
        /// Gets or sets the value of variable snapPath.
        /// </summary>
        [TestVariable("e83b4593-3316-48cc-92f2-eb601e378280")]
        public string snapPath
        {
            get { return _snapPath; }
            set { _snapPath = value; }
        }

        string _language;

        /// <summary>
        /// Gets or sets the value of variable language.
        /// </summary>
        [TestVariable("51979456-9c0d-49c4-8ca8-674678c8c3a1")]
        public string language
        {
            get { return _language; }
            set { _language = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MyProfile' at Center.", repo.CHROME.MyProfileInfo, new RecordItemIndex(1));
            repo.CHROME.MyProfile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.RegionalSettings' at Center.", repo.CHROME.MainFrame.RegionalSettingsInfo, new RecordItemIndex(2));
            repo.CHROME.MainFrame.RegionalSettings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Edit' at Center.", repo.CHROME.MainFrame.EditInfo, new RecordItemIndex(3));
            repo.CHROME.MainFrame.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '$language' on item 'CHROME.MainFrame.SelLang'.", repo.CHROME.MainFrame.SelLangInfo, new RecordItemIndex(4));
            repo.CHROME.MainFrame.SelLang.Element.SetAttributeValue("TagValue", language);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Submit' at Center.", repo.CHROME.MainFrame.SubmitInfo, new RecordItemIndex(5));
            repo.CHROME.MainFrame.Submit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+R' Press.", new RecordItemIndex(6));
            Keyboard.Press(System.Windows.Forms.Keys.R | System.Windows.Forms.Keys.Control, 19, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'CHROME'.", repo.CHROME.SelfInfo, new RecordItemIndex(7));
            Host.Current.KillApplication(repo.CHROME.Self);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/' with browser 'Firefox' in maximized mode.", new RecordItemIndex(8));
            Host.Current.OpenBrowser("https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/", "Firefox", "", false, true, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(9));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'F11' Press.", new RecordItemIndex(10));
            Keyboard.Press(System.Windows.Forms.Keys.F11, 19, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(11));
            Delay.Duration(8000, false);
            
            // A
            Report.Log(ReportLevel.Info, "Section", "A", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ToBm' at Center.", repo.MOZILLA.ToBmInfo, new RecordItemIndex(13));
            repo.MOZILLA.ToBm.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(14));
            Delay.Duration(4000, false);
            
            Snap(snapPath, "60");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Customers' at Center.", repo.MOZILLA.CustomersInfo, new RecordItemIndex(16));
            repo.MOZILLA.Customers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ATagMACRONSpol' at Center.", repo.MOZILLA.ATagMACRONSpolInfo, new RecordItemIndex(18));
            repo.MOZILLA.ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "61");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.BoxArea'.", repo.MOZILLA.BoxAreaInfo, new RecordItemIndex(20));
            repo.MOZILLA.BoxArea.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(21));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "62");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Documents' at Center.", repo.MOZILLA.DocumentsInfo, new RecordItemIndex(23));
            repo.MOZILLA.Documents.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ATagMACRONSpol' at Center.", repo.MOZILLA.ATagMACRONSpolInfo, new RecordItemIndex(26));
            repo.MOZILLA.ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(27));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "64");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentLog' at Center.", repo.MOZILLA.PaymentLogInfo, new RecordItemIndex(29));
            repo.MOZILLA.PaymentLog.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(30));
            Delay.Duration(2000, false);
            
            // payment method title??
            Snap(snapPath, "65");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.AccountHash1000001MACRONSpolSRO' at Center.", repo.MOZILLA.MainFrame.AccountHash1000001MACRONSpolSROInfo, new RecordItemIndex(32));
            //repo.MOZILLA.MainFrame.AccountHash1000001MACRONSpolSRO.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Customers' at Center.", repo.MOZILLA.CustomersInfo, new RecordItemIndex(33));
            repo.MOZILLA.Customers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ATagMACRONSpol' at Center.", repo.MOZILLA.ATagMACRONSpolInfo, new RecordItemIndex(34));
            repo.MOZILLA.ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(35));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.Notes' at Center.", repo.MOZILLA.MainFrame.NotesInfo, new RecordItemIndex(36));
            repo.MOZILLA.MainFrame.Notes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(37));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "66");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Orders' at Center.", repo.MOZILLA.OrdersInfo, new RecordItemIndex(39));
            repo.MOZILLA.Orders.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(40));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "67");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.AddNewOrder' at Center.", repo.MOZILLA.MainFrame.AddNewOrderInfo, new RecordItemIndex(42));
            repo.MOZILLA.MainFrame.AddNewOrder.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.HttpsPbaAMoriApsdemoOrg8443Bss' at Center.", repo.MOZILLA.MainFrame.HttpsPbaAMoriApsdemoOrg8443BssInfo, new RecordItemIndex(43));
            repo.MOZILLA.MainFrame.HttpsPbaAMoriApsdemoOrg8443Bss.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TdTagDomainInComZ' at Center.", repo.TdTagDomainInComZInfo, new RecordItemIndex(44));
            repo.TdTagDomainInComZ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.HttpsPbaAMoriApsdemoOrg8443Bss1' at Center.", repo.MOZILLA.MainFrame.HttpsPbaAMoriApsdemoOrg8443Bss1Info, new RecordItemIndex(45));
            repo.MOZILLA.MainFrame.HttpsPbaAMoriApsdemoOrg8443Bss1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TdTagDomainInComZ' at Center.", repo.TdTagDomainInComZInfo, new RecordItemIndex(46));
            repo.TdTagDomainInComZ.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "68");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.InputSaveAdd' at Center.", repo.MOZILLA.MainFrame.InputSaveAddInfo, new RecordItemIndex(48));
            repo.MOZILLA.MainFrame.InputSaveAdd.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "69");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.InputExit' at Center.", repo.MOZILLA.MainFrame.InputExitInfo, new RecordItemIndex(50));
            repo.MOZILLA.MainFrame.InputExit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.Users' at Center.", repo.MOZILLA.MainFrame.UsersInfo, new RecordItemIndex(51));
            repo.MOZILLA.MainFrame.Users.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ATagMACRONSpol' at Center.", repo.MOZILLA.ATagMACRONSpolInfo, new RecordItemIndex(52));
            repo.MOZILLA.ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "70");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.MainFrame.BtnsBox'.", repo.MOZILLA.MainFrame.BtnsBoxInfo, new RecordItemIndex(54));
            repo.MOZILLA.MainFrame.BtnsBox.EnsureVisible();
            Delay.Milliseconds(0);
            
            Snap(snapPath, "71");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.AccountHash1000001MACRONSpolSRO' at Center.", repo.MOZILLA.MainFrame.AccountHash1000001MACRONSpolSROInfo, new RecordItemIndex(56));
            //repo.MOZILLA.MainFrame.AccountHash1000001MACRONSpolSRO.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Customers' at Center.", repo.MOZILLA.CustomersInfo, new RecordItemIndex(57));
            repo.MOZILLA.Customers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(58));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ATagMACRONSpol' at Center.", repo.MOZILLA.ATagMACRONSpolInfo, new RecordItemIndex(59));
            repo.MOZILLA.ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentsMethods' at Center.", repo.MOZILLA.PaymentsMethodsInfo, new RecordItemIndex(60));
            repo.MOZILLA.PaymentsMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(61));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.cechkcash' at Center.", repo.MOZILLA.cechkcashInfo, new RecordItemIndex(62));
            repo.MOZILLA.cechkcash.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "72");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Tasks' at Center.", repo.MOZILLA.TasksInfo, new RecordItemIndex(64));
            repo.MOZILLA.Tasks.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(65));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(66));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(67));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "73");
            Delay.Milliseconds(0);
            
            // B
            Report.Log(ReportLevel.Info, "Section", "B", new RecordItemIndex(69));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Documents1' at Center.", repo.MOZILLA.LeftFrame.Documents1Info, new RecordItemIndex(70));
            repo.MOZILLA.LeftFrame.Documents1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(71));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.CreditMemos' at Center.", repo.MOZILLA.MainFrame.CreditMemosInfo, new RecordItemIndex(72));
            repo.MOZILLA.MainFrame.CreditMemos.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(73));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.AddNewCreditMemo' at Center.", repo.MOZILLA.MainFrame.AddNewCreditMemoInfo, new RecordItemIndex(74));
            repo.MOZILLA.MainFrame.AddNewCreditMemo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(75));
            Delay.Duration(3000, false);
            
            Snap(snapPath, "74");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Reports' at Center.", repo.MOZILLA.LeftFrame.ReportsInfo, new RecordItemIndex(77));
            repo.MOZILLA.LeftFrame.Reports.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(78));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "75");
            Delay.Milliseconds(0);
            
            // C
            Report.Log(ReportLevel.Info, "Section", "C", new RecordItemIndex(80));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.ServicePlans' at Center.", repo.MOZILLA.LeftFrame.ServicePlansInfo, new RecordItemIndex(81));
            repo.MOZILLA.LeftFrame.ServicePlans.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(82));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "76");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(84));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(85));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "77");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.MainFrame.BtnsBox'.", repo.MOZILLA.MainFrame.BtnsBoxInfo, new RecordItemIndex(87));
            repo.MOZILLA.MainFrame.BtnsBox.EnsureVisible();
            Delay.Milliseconds(0);
            
            Snap(snapPath, "77a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.subs' at Center.", repo.MOZILLA.subsInfo, new RecordItemIndex(89));
            repo.MOZILLA.subs.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(90));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "78");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Orders' at Center.", repo.MOZILLA.OrdersInfo, new RecordItemIndex(92));
            repo.MOZILLA.Orders.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(93));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.UpSales' at Center.", repo.MOZILLA.MainFrame.UpSalesInfo, new RecordItemIndex(95));
            repo.MOZILLA.MainFrame.UpSales.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(96));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "80");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.ServicePlans' at Center.", repo.MOZILLA.LeftFrame.ServicePlansInfo, new RecordItemIndex(98));
            repo.MOZILLA.LeftFrame.ServicePlans.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(99));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentsMethods' at Center.", repo.MOZILLA.PaymentsMethodsInfo, new RecordItemIndex(100));
            repo.MOZILLA.PaymentsMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(101));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "81");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SalesCategories' at Center.", repo.MOZILLA.MainFrame.SalesCategoriesInfo, new RecordItemIndex(103));
            repo.MOZILLA.MainFrame.SalesCategories.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(104));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "82");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Resources' at Center.", repo.MOZILLA.LeftFrame.ResourcesInfo, new RecordItemIndex(106));
            repo.MOZILLA.LeftFrame.Resources.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(107));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(108));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(109));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "83");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.MainFrame.BtnsBox'.", repo.MOZILLA.MainFrame.BtnsBoxInfo, new RecordItemIndex(111));
            repo.MOZILLA.MainFrame.BtnsBox.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(112));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "83a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.UpSales' at Center.", repo.MOZILLA.MainFrame.UpSalesInfo, new RecordItemIndex(114));
            repo.MOZILLA.MainFrame.UpSales.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(115));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "84");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Marketing' at Center.", repo.MOZILLA.LeftFrame.MarketingInfo, new RecordItemIndex(117));
            repo.MOZILLA.LeftFrame.Marketing.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(118));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(119));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(120));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "85");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.MainFrame.BtnsBox'.", repo.MOZILLA.MainFrame.BtnsBoxInfo, new RecordItemIndex(122));
            repo.MOZILLA.MainFrame.BtnsBox.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(123));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "85a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentsMethods' at Center.", repo.MOZILLA.PaymentsMethodsInfo, new RecordItemIndex(125));
            repo.MOZILLA.PaymentsMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(126));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(127));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(128));
            Delay.Duration(1000, false);
            
            Snap(snapPath, "86");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Marketing' at Center.", repo.MOZILLA.LeftFrame.MarketingInfo, new RecordItemIndex(130));
            repo.MOZILLA.LeftFrame.Marketing.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(131));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentLog' at Center.", repo.MOZILLA.PaymentLogInfo, new RecordItemIndex(132));
            repo.MOZILLA.PaymentLog.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "87");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.OnlineStore' at Center.", repo.MOZILLA.LeftFrame.OnlineStoreInfo, new RecordItemIndex(134));
            repo.MOZILLA.LeftFrame.OnlineStore.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(135));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(136));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.Copy_of_ATagMACRONSpol'.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(137));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(138));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(139));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "88");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.MainFrame.T1Title'.", repo.MOZILLA.MainFrame.T1TitleInfo, new RecordItemIndex(141));
            repo.MOZILLA.MainFrame.T1Title.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(142));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "88a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.OnlineStore' at Center.", repo.MOZILLA.LeftFrame.OnlineStoreInfo, new RecordItemIndex(144));
            repo.MOZILLA.LeftFrame.OnlineStore.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(145));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentsMethods' at Center.", repo.MOZILLA.PaymentsMethodsInfo, new RecordItemIndex(146));
            repo.MOZILLA.PaymentsMethods.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "89");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SalesCategories' at Center.", repo.MOZILLA.MainFrame.SalesCategoriesInfo, new RecordItemIndex(148));
            repo.MOZILLA.MainFrame.SalesCategories.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "90");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.UpSales' at Center.", repo.MOZILLA.MainFrame.UpSalesInfo, new RecordItemIndex(150));
            repo.MOZILLA.MainFrame.UpSales.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "91");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ATagMACRONSpol' at Center.", repo.MOZILLA.ATagMACRONSpolInfo, new RecordItemIndex(152));
            repo.MOZILLA.ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(153));
            Delay.Duration(3000, false);
            
            Snap(snapPath, "91a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.OnlineStore' at Center.", repo.MOZILLA.LeftFrame.OnlineStoreInfo, new RecordItemIndex(155));
            repo.MOZILLA.LeftFrame.OnlineStore.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(156));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.CreditMemos' at Center.", repo.MOZILLA.MainFrame.CreditMemosInfo, new RecordItemIndex(157));
            repo.MOZILLA.MainFrame.CreditMemos.Click();
            Delay.Milliseconds(200);
            
            // ?? str16, purchase scenario domain registration
            Snap(snapPath, "92");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.OnlineStore' at Center.", repo.MOZILLA.LeftFrame.OnlineStoreInfo, new RecordItemIndex(159));
            repo.MOZILLA.LeftFrame.OnlineStore.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(160));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Copy_of_ATagMACRONSpol' at Center.", repo.MOZILLA.Copy_of_ATagMACRONSpolInfo, new RecordItemIndex(161));
            repo.MOZILLA.Copy_of_ATagMACRONSpol.Click();
            Delay.Milliseconds(200);
            
            // ?? str16, purchase scenario domain registration
            Snap(snapPath, "92a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.OnlineStore' at Center.", repo.MOZILLA.LeftFrame.OnlineStoreInfo, new RecordItemIndex(163));
            repo.MOZILLA.LeftFrame.OnlineStore.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(164));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentLog' at Center.", repo.MOZILLA.PaymentLogInfo, new RecordItemIndex(165));
            repo.MOZILLA.PaymentLog.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.DirectLinks' at Center.", repo.MOZILLA.MainFrame.DirectLinksInfo, new RecordItemIndex(166));
            repo.MOZILLA.MainFrame.DirectLinks.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "93");
            Delay.Milliseconds(0);
            
            // D
            Report.Log(ReportLevel.Info, "Section", "D", new RecordItemIndex(168));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Users' at Center.", repo.MOZILLA.LeftFrame.UsersInfo, new RecordItemIndex(169));
            repo.MOZILLA.LeftFrame.Users.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(170));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.cechkcash' at Center.", repo.MOZILLA.cechkcashInfo, new RecordItemIndex(171));
            repo.MOZILLA.cechkcash.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentsMethods' at Center.", repo.MOZILLA.PaymentsMethodsInfo, new RecordItemIndex(172));
            repo.MOZILLA.PaymentsMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(173));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "94");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(175));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(176));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "95");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetOperationsECommerce' at Center.", repo.MOZILLA.MainFrame.SysSetOperationsECommerceInfo, new RecordItemIndex(178));
            repo.MOZILLA.MainFrame.SysSetOperationsECommerce.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(179));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "96");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(181));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(182));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetOperationsECommerceKeysManag' at Center.", repo.MOZILLA.MainFrame.SysSetOperationsECommerceKeysManagInfo, new RecordItemIndex(183));
            repo.MOZILLA.MainFrame.SysSetOperationsECommerceKeysManag.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "97");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(185));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetOperationsAttrSettings' at Center.", repo.MOZILLA.MainFrame.SysSetOperationsAttrSettingsInfo, new RecordItemIndex(186));
            repo.MOZILLA.MainFrame.SysSetOperationsAttrSettings.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "98");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(188));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(189));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetOperationsOrderProcessing' at Center.", repo.MOZILLA.MainFrame.SysSetOperationsOrderProcessingInfo, new RecordItemIndex(190));
            repo.MOZILLA.MainFrame.SysSetOperationsOrderProcessing.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(191));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetOperationsOrderProcessingGrou' at Center.", repo.MOZILLA.MainFrame.SysSetOperationsOrderProcessingGrouInfo, new RecordItemIndex(193));
            repo.MOZILLA.MainFrame.SysSetOperationsOrderProcessingGrou.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(194));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(196));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetSystemMyAccInf' at Center.", repo.MOZILLA.MainFrame.SysSetSystemMyAccInfInfo, new RecordItemIndex(197));
            repo.MOZILLA.MainFrame.SysSetSystemMyAccInf.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(198));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "101");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(200));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetSystemIntern' at Center.", repo.MOZILLA.MainFrame.SysSetSystemInternInfo, new RecordItemIndex(201));
            repo.MOZILLA.MainFrame.SysSetSystemIntern.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(202));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "102");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(204));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetSystemSecurity' at Center.", repo.MOZILLA.MainFrame.SysSetSystemSecurityInfo, new RecordItemIndex(205));
            repo.MOZILLA.MainFrame.SysSetSystemSecurity.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(206));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "103");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(208));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetSystemMessaging' at Center.", repo.MOZILLA.MainFrame.SysSetSystemMessagingInfo, new RecordItemIndex(209));
            repo.MOZILLA.MainFrame.SysSetSystemMessaging.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentsMethods' at Center.", repo.MOZILLA.PaymentsMethodsInfo, new RecordItemIndex(210));
            repo.MOZILLA.PaymentsMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(211));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "104");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(213));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetSystemReporting' at Center.", repo.MOZILLA.MainFrame.SysSetSystemReportingInfo, new RecordItemIndex(214));
            repo.MOZILLA.MainFrame.SysSetSystemReporting.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(215));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "105");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(217));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetFinancesTaxes' at Center.", repo.MOZILLA.MainFrame.SysSetFinancesTaxesInfo, new RecordItemIndex(218));
            repo.MOZILLA.MainFrame.SysSetFinancesTaxes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(219));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "106");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(221));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetFinancesTerms' at Center.", repo.MOZILLA.MainFrame.SysSetFinancesTermsInfo, new RecordItemIndex(222));
            repo.MOZILLA.MainFrame.SysSetFinancesTerms.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentLog' at Center.", repo.MOZILLA.PaymentLogInfo, new RecordItemIndex(223));
            repo.MOZILLA.PaymentLog.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(224));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "107");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(226));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetFinancesOther' at Center.", repo.MOZILLA.MainFrame.SysSetFinancesOtherInfo, new RecordItemIndex(227));
            repo.MOZILLA.MainFrame.SysSetFinancesOther.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(228));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "108");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(230));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetProductsMeasurement' at Center.", repo.MOZILLA.MainFrame.SysSetProductsMeasurementInfo, new RecordItemIndex(231));
            repo.MOZILLA.MainFrame.SysSetProductsMeasurement.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "109");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Settings' at Center.", repo.MOZILLA.LeftFrame.SettingsInfo, new RecordItemIndex(233));
            repo.MOZILLA.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.SysSetProductsSku' at Center.", repo.MOZILLA.MainFrame.SysSetProductsSkuInfo, new RecordItemIndex(234));
            repo.MOZILLA.MainFrame.SysSetProductsSku.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(235));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "110");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
