///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Odin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ControlPanel recording.
    /// </summary>
    [TestModule("ebe349c9-3770-48a7-910f-6f4757cdb54c", ModuleType.Recording, 1)]
    public partial class ControlPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OdinRepository repository.
        /// </summary>
        public static OdinRepository repo = OdinRepository.Instance;

        static ControlPanel instance = new ControlPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ControlPanel()
        {
            language = "en_US";
            snapPath = "c:\\Users\\LMeskova\\Documents\\Ranorex\\RanorexStudio Projects\\Odin\\Odin\\_files\\Screens\\RUS\\";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ControlPanel Instance
        {
            get { return instance; }
        }

#region Variables

        string _language;

        /// <summary>
        /// Gets or sets the value of variable language.
        /// </summary>
        [TestVariable("05fb999b-0af0-455b-82d8-b00caa749be1")]
        public string language
        {
            get { return _language; }
            set { _language = value; }
        }

        string _snapPath;

        /// <summary>
        /// Gets or sets the value of variable snapPath.
        /// </summary>
        [TestVariable("8c61e8a4-6c02-4199-a603-40b5877d83e1")]
        public string snapPath
        {
            get { return _snapPath; }
            set { _snapPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/", "Chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(1));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MyProfile' at Center.", repo.CHROME.MyProfileInfo, new RecordItemIndex(2));
            repo.CHROME.MyProfile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.RegionalSettings' at Center.", repo.CHROME.MainFrame.RegionalSettingsInfo, new RecordItemIndex(3));
            repo.CHROME.MainFrame.RegionalSettings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Edit' at Center.", repo.CHROME.MainFrame.EditInfo, new RecordItemIndex(4));
            repo.CHROME.MainFrame.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '$language' on item 'CHROME.MainFrame.SelLang'.", repo.CHROME.MainFrame.SelLangInfo, new RecordItemIndex(5));
            repo.CHROME.MainFrame.SelLang.Element.SetAttributeValue("TagValue", language);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Submit' at Center.", repo.CHROME.MainFrame.SubmitInfo, new RecordItemIndex(6));
            repo.CHROME.MainFrame.Submit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'CHROME'.", repo.CHROME.SelfInfo, new RecordItemIndex(7));
            Host.Current.KillApplication(repo.CHROME.Self);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/' with browser 'Firefox' in maximized mode.", new RecordItemIndex(8));
            Host.Current.OpenBrowser("https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/", "Firefox", "", false, true, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(9));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'F11' Press.", new RecordItemIndex(10));
            Keyboard.Press(System.Windows.Forms.Keys.F11, 19, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(11));
            Delay.Duration(8000, false);
            
            // A
            Report.Log(ReportLevel.Info, "Section", "A", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Customers' at Center.", repo.MOZILLA.LeftFrame.CustomersInfo, new RecordItemIndex(13));
            repo.MOZILLA.LeftFrame.Customers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.HttpAMoriApsdemoOrg8080PemImage' at Center.", repo.MOZILLA.MainFrame.HttpAMoriApsdemoOrg8080PemImageInfo, new RecordItemIndex(14));
            repo.MOZILLA.MainFrame.HttpAMoriApsdemoOrg8080PemImage.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(15));
            Delay.Duration(6000, false);
            
            Snap(snapPath, "111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpAMoriApsdemoOrg8080CcpIPa' at Center.", repo.HttpAMoriApsdemoOrg8080CcpIPaInfo, new RecordItemIndex(17));
            repo.HttpAMoriApsdemoOrg8080CcpIPa.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.UniqName33Button0Button' at Center.", repo.MOZILLA.UniqName33Button0ButtonInfo, new RecordItemIndex(18));
            repo.MOZILLA.UniqName33Button0Button.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.UniqName33Button0Item0' at Center.", repo.MOZILLA.UniqName33Button0Item0Info, new RecordItemIndex(19));
            repo.MOZILLA.UniqName33Button0Item0.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(20));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "112");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpAMoriApsdemoOrg8080CcpIPa' at Center.", repo.HttpAMoriApsdemoOrg8080CcpIPaInfo, new RecordItemIndex(22));
            repo.HttpAMoriApsdemoOrg8080CcpIPa.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.AddNewUsersInTile' at Center.", repo.MOZILLA.AddNewUsersInTileInfo, new RecordItemIndex(23));
            repo.MOZILLA.AddNewUsersInTile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "113");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.FaFaShoppingCart' at 9;14.", repo.MOZILLA.FaFaShoppingCartInfo, new RecordItemIndex(26));
            repo.MOZILLA.FaFaShoppingCart.Click("9;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PanelTitle' at Center.", repo.MOZILLA.PanelTitleInfo, new RecordItemIndex(27));
            repo.MOZILLA.PanelTitle.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(28));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "114");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.HttpWwwParallelsComCcpDomains.PanelBodyCollapseIn' at Center.", repo.MOZILLA.HttpWwwParallelsComCcpDomains.PanelBodyCollapseInInfo, new RecordItemIndex(30));
            repo.MOZILLA.HttpWwwParallelsComCcpDomains.PanelBodyCollapseIn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransfer' at Center.", repo.MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransferInfo, new RecordItemIndex(31));
            repo.MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransfer.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bla.net' with focus on 'MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransfer'.", repo.MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransferInfo, new RecordItemIndex(32));
            repo.MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransfer.PressKeys("bla.net");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransfer'.", repo.MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransferInfo, new RecordItemIndex(33));
            repo.MOZILLA.HttpWwwParallelsComCcpDomains.RegisterDomainDomainNameToTransfer.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'MOZILLA.HttpWwwParallelsComCcpDomains.PanelBodyCollapseIn1'.", repo.MOZILLA.HttpWwwParallelsComCcpDomains.PanelBodyCollapseIn1Info, new RecordItemIndex(34));
            repo.MOZILLA.HttpWwwParallelsComCcpDomains.PanelBodyCollapseIn1.EnsureVisible();
            Delay.Milliseconds(0);
            
            Snap(snapPath, "115");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.Account' at Center.", repo.MOZILLA.AccountInfo, new RecordItemIndex(36));
            repo.MOZILLA.Account.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(37));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "116");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentMethods' at Center.", repo.MOZILLA.PaymentMethodsInfo, new RecordItemIndex(39));
            repo.MOZILLA.PaymentMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(40));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "117");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.ActionLog' at Center.", repo.MOZILLA.ActionLogInfo, new RecordItemIndex(42));
            repo.MOZILLA.ActionLog.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(43));
            Delay.Duration(2000, false);
            
            Snap(snapPath, "118");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'MOZILLA'.", repo.MOZILLA.SelfInfo, new RecordItemIndex(45));
            Host.Current.KillApplication(repo.MOZILLA.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
