///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Odin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Office365Module recording.
    /// </summary>
    [TestModule("99243033-4693-4325-a2c3-d22c428c7528", ModuleType.Recording, 1)]
    public partial class Office365Module : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OdinRepository repository.
        /// </summary>
        public static OdinRepository repo = OdinRepository.Instance;

        static Office365Module instance = new Office365Module();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Office365Module()
        {
            language = "en_US";
            snapPath = "c:\\Users\\LMeskova\\Documents\\Ranorex\\RanorexStudio Projects\\Odin\\Odin\\_files\\Screens\\RUS\\";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Office365Module Instance
        {
            get { return instance; }
        }

#region Variables

        string _language;

        /// <summary>
        /// Gets or sets the value of variable language.
        /// </summary>
        [TestVariable("a2181628-dea5-437e-aa1f-b375ffc06806")]
        public string language
        {
            get { return _language; }
            set { _language = value; }
        }

        string _snapPath;

        /// <summary>
        /// Gets or sets the value of variable snapPath.
        /// </summary>
        [TestVariable("d74da497-734b-4667-81b1-dbc096505235")]
        public string snapPath
        {
            get { return _snapPath; }
            set { _snapPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/", "Chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MyProfile' at Center.", repo.CHROME.MyProfileInfo, new RecordItemIndex(1));
            repo.CHROME.MyProfile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.RegionalSettings' at Center.", repo.CHROME.MainFrame.RegionalSettingsInfo, new RecordItemIndex(2));
            repo.CHROME.MainFrame.RegionalSettings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Edit' at Center.", repo.CHROME.MainFrame.EditInfo, new RecordItemIndex(3));
            repo.CHROME.MainFrame.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '$language' on item 'CHROME.MainFrame.SelLang'.", repo.CHROME.MainFrame.SelLangInfo, new RecordItemIndex(4));
            repo.CHROME.MainFrame.SelLang.Element.SetAttributeValue("TagValue", language);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Submit' at Center.", repo.CHROME.MainFrame.SubmitInfo, new RecordItemIndex(5));
            repo.CHROME.MainFrame.Submit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'CHROME'.", repo.CHROME.SelfInfo, new RecordItemIndex(6));
            Host.Current.KillApplication(repo.CHROME.Self);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://osapub2.extest.apsdemo.org:8080/workspace.html?bw_id=4b80d8c44d57e8685ffda9be1f02bd92&cp=prv' with browser 'firefox' in maximized mode.", new RecordItemIndex(7));
            Host.Current.OpenBrowser("http://osapub2.extest.apsdemo.org:8080/workspace.html?bw_id=4b80d8c44d57e8685ffda9be1f02bd92&cp=prv", "firefox", "", false, true, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(8));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}M{RShiftKey up}oravia'.", new RecordItemIndex(9));
            Keyboard.Press("{RShiftKey down}M{RShiftKey up}oravia");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(10));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(11));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'F11' Press.", new RecordItemIndex(12));
            Keyboard.Press(System.Windows.Forms.Keys.F11, 19, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(13));
            Delay.Duration(8000, false);
            
            // A
            Report.Log(ReportLevel.Info, "Section", "A", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.LeftFrame.Office365' at Center.", repo.MOZILLA.LeftFrame.Office365Info, new RecordItemIndex(15));
            repo.MOZILLA.LeftFrame.Office365.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(16));
            Delay.Duration(6000, false);
            
            Snap(snapPath, "119");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking EnsureVisible() on item 'BoxArea'.", repo.BoxAreaInfo, new RecordItemIndex(18));
            repo.BoxArea.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(19));
            Delay.Duration(4000, false);
            
            Snap(snapPath, "119a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.LicenseTypes' at Center.", repo.MOZILLA.MainFrame.LicenseTypesInfo, new RecordItemIndex(21));
            repo.MOZILLA.MainFrame.LicenseTypes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(22));
            Delay.Duration(4000, false);
            
            Snap(snapPath, "120");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.AddonTypes' at Center.", repo.MOZILLA.MainFrame.AddonTypesInfo, new RecordItemIndex(24));
            repo.MOZILLA.MainFrame.AddonTypes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(25));
            Delay.Duration(4000, false);
            
            Snap(snapPath, "121");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.Statistics' at Center.", repo.MOZILLA.MainFrame.StatisticsInfo, new RecordItemIndex(27));
            repo.MOZILLA.MainFrame.Statistics.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(28));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.MainFrame.ViewHowTheTotalNumbersOfSubscripti' at Center.", repo.MOZILLA.MainFrame.ViewHowTheTotalNumbersOfSubscriptiInfo, new RecordItemIndex(29));
            repo.MOZILLA.MainFrame.ViewHowTheTotalNumbersOfSubscripti.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(30));
            Delay.Duration(4000, false);
            
            Snap(snapPath, "122");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MOZILLA.PaymentLog' at Center.", repo.MOZILLA.PaymentLogInfo, new RecordItemIndex(32));
            repo.MOZILLA.PaymentLog.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(33));
            Delay.Duration(4000, false);
            
            Snap(snapPath, "123");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
