///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Odin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OperationsModule recording.
    /// </summary>
    [TestModule("d3e3c362-2822-4287-8974-62df7c04af07", ModuleType.Recording, 1)]
    public partial class OperationsModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OdinRepository repository.
        /// </summary>
        public static OdinRepository repo = OdinRepository.Instance;

        static OperationsModule instance = new OperationsModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OperationsModule()
        {
            snapPath = "c:\\Users\\LMeskova\\Documents\\Odin\\Screens\\";
            language = "en_US";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OperationsModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _snapPath;

        /// <summary>
        /// Gets or sets the value of variable snapPath.
        /// </summary>
        [TestVariable("7c44b59f-1ada-42c4-9f5e-301ef07ec7ac")]
        public string snapPath
        {
            get { return _snapPath; }
            set { _snapPath = value; }
        }

        string _language;

        /// <summary>
        /// Gets or sets the value of variable language.
        /// </summary>
        [TestVariable("6de8c967-bfd5-4932-9688-0e0628137e12")]
        public string language
        {
            get { return _language; }
            set { _language = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://dev.apsstandard.org/develop/orgs/mori/sandboxes/a/pcp/", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MyProfile' at Center.", repo.CHROME.MyProfileInfo, new RecordItemIndex(1));
            repo.CHROME.MyProfile.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.RegionalSettings' at Center.", repo.CHROME.MainFrame.RegionalSettingsInfo, new RecordItemIndex(2));
            repo.CHROME.MainFrame.RegionalSettings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Edit' at Center.", repo.CHROME.MainFrame.EditInfo, new RecordItemIndex(3));
            repo.CHROME.MainFrame.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '$language' on item 'CHROME.MainFrame.SelLang'.", repo.CHROME.MainFrame.SelLangInfo, new RecordItemIndex(4));
            repo.CHROME.MainFrame.SelLang.Element.SetAttributeValue("TagValue", language);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Submit' at Center.", repo.CHROME.MainFrame.SubmitInfo, new RecordItemIndex(5));
            repo.CHROME.MainFrame.Submit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+R' Press.", new RecordItemIndex(6));
            Keyboard.Press(System.Windows.Forms.Keys.R | System.Windows.Forms.Keys.Control, 19, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            Delay.Duration(5000, false);
            
            // A
            Report.Log(ReportLevel.Info, "Section", "A", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MoraviaTest' at 44;9.", repo.CHROME.MoraviaTestInfo, new RecordItemIndex(9));
            repo.CHROME.MoraviaTest.Click("44;9");
            Delay.Milliseconds(200);
            
            Snap(snapPath, "01");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Customers' at Center.", repo.CHROME.LeftFrame.CustomersInfo, new RecordItemIndex(11));
            repo.CHROME.LeftFrame.Customers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ObjectAccount1' at Center.", repo.CHROME.MainFrame.ObjectAccount1Info, new RecordItemIndex(12));
            repo.CHROME.MainFrame.ObjectAccount1.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "02");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.General' at Center.", repo.CHROME.MainFrame.GeneralInfo, new RecordItemIndex(14));
            repo.CHROME.MainFrame.General.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "03");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Resources' at Center.", repo.CHROME.MainFrame.ResourcesInfo, new RecordItemIndex(16));
            repo.CHROME.MainFrame.Resources.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.IPPools' at Center.", repo.CHROME.MainFrame.IPPoolsInfo, new RecordItemIndex(17));
            repo.CHROME.MainFrame.IPPools.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "04");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Security' at Center.", repo.CHROME.MainFrame.SecurityInfo, new RecordItemIndex(19));
            repo.CHROME.MainFrame.Security.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "05");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.General' at Center.", repo.CHROME.MainFrame.GeneralInfo, new RecordItemIndex(21));
            repo.CHROME.MainFrame.General.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ServiceUsers' at Center.", repo.CHROME.MainFrame.ServiceUsersInfo, new RecordItemIndex(22));
            repo.CHROME.MainFrame.ServiceUsers.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "06");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Repository' at Center.", repo.CHROME.MainFrame.RepositoryInfo, new RecordItemIndex(24));
            repo.CHROME.MainFrame.Repository.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "07");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.UploadItem' at Center.", repo.CHROME.MainFrame.UploadItemInfo, new RecordItemIndex(26));
            repo.CHROME.MainFrame.UploadItem.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.SelItemType' at Center.", repo.CHROME.MainFrame.SelItemTypeInfo, new RecordItemIndex(27));
            repo.CHROME.MainFrame.SelItemType.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "08");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Tasks' at 14;10.", repo.CHROME.LeftFrame.TasksInfo, new RecordItemIndex(29));
            repo.CHROME.LeftFrame.Tasks.Click("14;10");
            Delay.Milliseconds(200);
            
            Snap(snapPath, "09");
            Delay.Milliseconds(0);
            
            // B
            Report.Log(ReportLevel.Info, "Section", "B", new RecordItemIndex(31));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.ServiceTemplates' at Center.", repo.CHROME.LeftFrame.ServiceTemplatesInfo, new RecordItemIndex(32));
            repo.CHROME.LeftFrame.ServiceTemplates.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.AddNewServiceTemplate' at Center.", repo.CHROME.MainFrame.AddNewServiceTemplateInfo, new RecordItemIndex(33));
            repo.CHROME.MainFrame.AddNewServiceTemplate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.SelStType' at Center.", repo.CHROME.MainFrame.SelStTypeInfo, new RecordItemIndex(34));
            repo.CHROME.MainFrame.SelStType.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Cancel' at Center.", repo.CHROME.MainFrame.CancelInfo, new RecordItemIndex(36));
            repo.CHROME.MainFrame.Cancel.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'CHROME.MainFrame.Cancel' at Center.", repo.CHROME.MainFrame.CancelInfo, new RecordItemIndex(37));
                repo.CHROME.MainFrame.Cancel.Click();
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(37)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ServiceTemplatesGeneralView' at Center.", repo.CHROME.MainFrame.ServiceTemplatesGeneralViewInfo, new RecordItemIndex(38));
            repo.CHROME.MainFrame.ServiceTemplatesGeneralView.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Resources' at Center.", repo.CHROME.MainFrame.ResourcesInfo, new RecordItemIndex(40));
            repo.CHROME.MainFrame.Resources.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Parameters' at Center.", repo.CHROME.MainFrame.ParametersInfo, new RecordItemIndex(42));
            repo.CHROME.MainFrame.Parameters.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Resources' at Center.", repo.CHROME.LeftFrame.ResourcesInfo, new RecordItemIndex(44));
            repo.CHROME.LeftFrame.Resources.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.RtstResourceTypeHandlerDoSelect' at Center.", repo.CHROME.MainFrame.RtstResourceTypeHandlerDoSelectInfo, new RecordItemIndex(45));
            repo.CHROME.MainFrame.RtstResourceTypeHandlerDoSelect.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ProvisioningAttributes' at Center.", repo.CHROME.MainFrame.ProvisioningAttributesInfo, new RecordItemIndex(47));
            repo.CHROME.MainFrame.ProvisioningAttributes.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Resources' at Center.", repo.CHROME.LeftFrame.ResourcesInfo, new RecordItemIndex(49));
            repo.CHROME.LeftFrame.Resources.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ResourceClasses' at Center.", repo.CHROME.MainFrame.ResourceClassesInfo, new RecordItemIndex(50));
            repo.CHROME.MainFrame.ResourceClasses.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PcpResusageResUsageHandlerDoSubs' at Center.", repo.CHROME.MainFrame.PcpResusageResUsageHandlerDoSubsInfo, new RecordItemIndex(51));
            repo.CHROME.MainFrame.PcpResusageResUsageHandlerDoSubs.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PcpAccountSubsAccountSubPrepDoPerfor' at Center.", repo.CHROME.MainFrame.PcpAccountSubsAccountSubPrepDoPerforInfo, new RecordItemIndex(52));
            repo.CHROME.MainFrame.PcpAccountSubsAccountSubPrepDoPerfor.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Resources' at Center.", repo.CHROME.LeftFrame.ResourcesInfo, new RecordItemIndex(54));
            repo.CHROME.LeftFrame.Resources.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Attributes' at Center.", repo.CHROME.MainFrame.AttributesInfo, new RecordItemIndex(55));
            repo.CHROME.MainFrame.Attributes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PcpAccountAttributesAttributesHandler' at Center.", repo.CHROME.MainFrame.PcpAccountAttributesAttributesHandlerInfo, new RecordItemIndex(56));
            repo.CHROME.MainFrame.PcpAccountAttributesAttributesHandler.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Hosts' at Center.", repo.CHROME.MainFrame.HostsInfo, new RecordItemIndex(57));
            repo.CHROME.MainFrame.Hosts.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "17");
            Delay.Milliseconds(0);
            
            // C
            Report.Log(ReportLevel.Info, "Section", "C", new RecordItemIndex(59));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Domains' at 28;19.", repo.CHROME.LeftFrame.DomainsInfo, new RecordItemIndex(60));
            repo.CHROME.LeftFrame.Domains.Click("28;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PcpDomainsHandlerDoSelect1' at Center.", repo.CHROME.MainFrame.PcpDomainsHandlerDoSelect1Info, new RecordItemIndex(61));
            repo.CHROME.MainFrame.PcpDomainsHandlerDoSelect1.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT' at Center.", repo.CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletTInfo, new RecordItemIndex(63));
            repo.CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ZoneSettings' at Center.", repo.CHROME.MainFrame.ZoneSettingsInfo, new RecordItemIndex(64));
            repo.CHROME.MainFrame.ZoneSettings.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Domains' at Center.", repo.CHROME.LeftFrame.DomainsInfo, new RecordItemIndex(66));
            repo.CHROME.LeftFrame.Domains.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.SpanTagDNS' at Center.", repo.CHROME.MainFrame.SpanTagDNSInfo, new RecordItemIndex(67));
            repo.CHROME.MainFrame.SpanTagDNS.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.WebHosting' at Center.", repo.CHROME.LeftFrame.WebHostingInfo, new RecordItemIndex(69));
            repo.CHROME.LeftFrame.WebHosting.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ManageConfigurations' at Center.", repo.CHROME.MainFrame.ManageConfigurationsInfo, new RecordItemIndex(71));
            repo.CHROME.MainFrame.ManageConfigurations.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.GroupConfigurationGroupsMultHandlerDo' at Center.", repo.CHROME.MainFrame.GroupConfigurationGroupsMultHandlerDoInfo, new RecordItemIndex(72));
            repo.CHROME.MainFrame.GroupConfigurationGroupsMultHandlerDo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PHPConfiguration' at Center.", repo.CHROME.MainFrame.PHPConfigurationInfo, new RecordItemIndex(73));
            repo.CHROME.MainFrame.PHPConfiguration.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Session' at Center.", repo.CHROME.MainFrame.SessionInfo, new RecordItemIndex(74));
            repo.CHROME.MainFrame.Session.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Applications' at Center.", repo.CHROME.LeftFrame.ApplicationsInfo, new RecordItemIndex(76));
            repo.CHROME.LeftFrame.Applications.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ApsPackagesView2' at Center.", repo.CHROME.MainFrame.ApsPackagesView2Info, new RecordItemIndex(78));
            repo.CHROME.MainFrame.ApsPackagesView2.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.CloudInfrastructure' at Center.", repo.CHROME.LeftFrame.CloudInfrastructureInfo, new RecordItemIndex(80));
            repo.CHROME.LeftFrame.CloudInfrastructure.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.MigrationTasks' at Center.", repo.CHROME.MainFrame.MigrationTasksInfo, new RecordItemIndex(81));
            repo.CHROME.MainFrame.MigrationTasks.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.TasksExecutionLog' at Center.", repo.CHROME.MainFrame.TasksExecutionLogInfo, new RecordItemIndex(83));
            repo.CHROME.MainFrame.TasksExecutionLog.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.CloudInfrastructure' at Center.", repo.CHROME.LeftFrame.CloudInfrastructureInfo, new RecordItemIndex(85));
            repo.CHROME.LeftFrame.CloudInfrastructure.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Setup' at Center.", repo.CHROME.MainFrame.SetupInfo, new RecordItemIndex(86));
            repo.CHROME.MainFrame.Setup.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.VPSBackupSchedules' at Center.", repo.CHROME.MainFrame.VPSBackupSchedulesInfo, new RecordItemIndex(88));
            repo.CHROME.MainFrame.VPSBackupSchedules.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.DomainRegistrars' at Center.", repo.CHROME.LeftFrame.DomainRegistrarsInfo, new RecordItemIndex(90));
            repo.CHROME.LeftFrame.DomainRegistrars.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT1' at Center.", repo.CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT1Info, new RecordItemIndex(91));
            repo.CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT1.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.CcwhoisVerisignGrsCom' at Center.", repo.CHROME.MainFrame.CcwhoisVerisignGrsComInfo, new RecordItemIndex(93));
            repo.CHROME.MainFrame.CcwhoisVerisignGrsCom.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "30");
            Delay.Milliseconds(0);
            
            // D
            Report.Log(ReportLevel.Info, "Section", "D", new RecordItemIndex(95));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.ServiceNodes' at Center.", repo.CHROME.LeftFrame.ServiceNodesInfo, new RecordItemIndex(96));
            repo.CHROME.LeftFrame.ServiceNodes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ObjectHost' at Center.", repo.CHROME.MainFrame.ObjectHostInfo, new RecordItemIndex(97));
            repo.CHROME.MainFrame.ObjectHost.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.General1' at Center.", repo.CHROME.MainFrame.General1Info, new RecordItemIndex(99));
            repo.CHROME.MainFrame.General1.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ProvisioningConfiguration' at Center.", repo.CHROME.MainFrame.ProvisioningConfigurationInfo, new RecordItemIndex(101));
            repo.CHROME.MainFrame.ProvisioningConfiguration.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Networking' at Center.", repo.CHROME.MainFrame.NetworkingInfo, new RecordItemIndex(103));
            repo.CHROME.MainFrame.Networking.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.IPAddresses' at Center.", repo.CHROME.MainFrame.IPAddressesInfo, new RecordItemIndex(105));
            repo.CHROME.MainFrame.IPAddresses.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "35");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Packages' at Center.", repo.CHROME.MainFrame.PackagesInfo, new RecordItemIndex(107));
            repo.CHROME.MainFrame.Packages.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.IPAddresses' at Center.", repo.CHROME.LeftFrame.IPAddressesInfo, new RecordItemIndex(109));
            repo.CHROME.LeftFrame.IPAddresses.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PcpAccountIpPoolsIPPoolsMultHandler' at UpperCenter.", repo.CHROME.MainFrame.PcpAccountIpPoolsIPPoolsMultHandlerInfo, new RecordItemIndex(110));
            repo.CHROME.MainFrame.PcpAccountIpPoolsIPPoolsMultHandler.Click(Location.UpperCenter);
            Delay.Milliseconds(200);
            
            Snap(snapPath, "37");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.IPAddresses' at Center.", repo.CHROME.LeftFrame.IPAddressesInfo, new RecordItemIndex(112));
            repo.CHROME.LeftFrame.IPAddresses.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT' at Center.", repo.CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletTInfo, new RecordItemIndex(113));
            repo.CHROME.MainFrame.HttpAMoriApsdemoOrg8080ServletT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.AddNewIPTranslation' at Center.", repo.CHROME.MainFrame.AddNewIPTranslationInfo, new RecordItemIndex(114));
            repo.CHROME.MainFrame.AddNewIPTranslation.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "38");
            Delay.Milliseconds(0);
            
            // E
            Report.Log(ReportLevel.Info, "Section", "E", new RecordItemIndex(116));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Information' at Center.", repo.CHROME.LeftFrame.InformationInfo, new RecordItemIndex(117));
            repo.CHROME.LeftFrame.Information.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.AvailableUpdates' at Center.", repo.CHROME.MainFrame.AvailableUpdatesInfo, new RecordItemIndex(119));
            repo.CHROME.MainFrame.AvailableUpdates.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "40");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.SupportContacts' at Center.", repo.CHROME.MainFrame.SupportContactsInfo, new RecordItemIndex(121));
            repo.CHROME.MainFrame.SupportContacts.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ProductLicense' at Center.", repo.CHROME.MainFrame.ProductLicenseInfo, new RecordItemIndex(123));
            repo.CHROME.MainFrame.ProductLicense.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.LicenseItems' at Center.", repo.CHROME.MainFrame.LicenseItemsInfo, new RecordItemIndex(125));
            repo.CHROME.MainFrame.LicenseItems.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "43");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Users' at Center.", repo.CHROME.LeftFrame.UsersInfo, new RecordItemIndex(127));
            repo.CHROME.LeftFrame.Users.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "44");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.LoginHistory' at Center.", repo.CHROME.MainFrame.LoginHistoryInfo, new RecordItemIndex(129));
            repo.CHROME.MainFrame.LoginHistory.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Sessions' at Center.", repo.CHROME.MainFrame.SessionsInfo, new RecordItemIndex(131));
            repo.CHROME.MainFrame.Sessions.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "46");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Announcements' at Center.", repo.CHROME.LeftFrame.AnnouncementsInfo, new RecordItemIndex(133));
            repo.CHROME.LeftFrame.Announcements.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Notifications' at Center.", repo.CHROME.MainFrame.NotificationsInfo, new RecordItemIndex(134));
            repo.CHROME.MainFrame.Notifications.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "47");
            Delay.Milliseconds(0);
            
            // F
            Report.Log(ReportLevel.Info, "Section", "F", new RecordItemIndex(136));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(137));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "48");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.RegionalSettings' at Center.", repo.CHROME.MainFrame.RegionalSettingsInfo, new RecordItemIndex(139));
            repo.CHROME.MainFrame.RegionalSettings.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "49");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(141));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Copy_of_Security1' at Center.", repo.CHROME.MainFrame.Copy_of_Security1Info, new RecordItemIndex(142));
            repo.CHROME.MainFrame.Copy_of_Security1.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(144));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Brands' at Center.", repo.CHROME.MainFrame.BrandsInfo, new RecordItemIndex(145));
            repo.CHROME.MainFrame.Brands.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.BrandingView' at Center.", repo.CHROME.MainFrame.BrandingViewInfo, new RecordItemIndex(146));
            repo.CHROME.MainFrame.BrandingView.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "51");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.ServiceBranding' at Center.", repo.CHROME.MainFrame.ServiceBrandingInfo, new RecordItemIndex(148));
            repo.CHROME.MainFrame.ServiceBranding.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.WebAnalyticsIntegration' at Center.", repo.CHROME.MainFrame.WebAnalyticsIntegrationInfo, new RecordItemIndex(150));
            repo.CHROME.MainFrame.WebAnalyticsIntegration.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "53");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.Certificate' at Center.", repo.CHROME.MainFrame.CertificateInfo, new RecordItemIndex(152));
            repo.CHROME.MainFrame.Certificate.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "54");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(154));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.CustomerCPNavigation' at Center.", repo.CHROME.MainFrame.CustomerCPNavigationInfo, new RecordItemIndex(155));
            repo.CHROME.MainFrame.CustomerCPNavigation.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "55");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(157));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.EnableDisableCCPV2' at Center.", repo.CHROME.MainFrame.EnableDisableCCPV2Info, new RecordItemIndex(158));
            repo.CHROME.MainFrame.EnableDisableCCPV2.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "56");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(160));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.EventHandling' at Center.", repo.CHROME.MainFrame.EventHandlingInfo, new RecordItemIndex(161));
            repo.CHROME.MainFrame.EventHandling.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.EventsHandlersView' at Center.", repo.CHROME.MainFrame.EventsHandlersViewInfo, new RecordItemIndex(162));
            repo.CHROME.MainFrame.EventsHandlersView.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.AddAction' at Center.", repo.CHROME.MainFrame.AddActionInfo, new RecordItemIndex(163));
            repo.CHROME.MainFrame.AddAction.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.EventsActionsView' at Center.", repo.CHROME.MainFrame.EventsActionsViewInfo, new RecordItemIndex(164));
            repo.CHROME.MainFrame.EventsActionsView.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "57");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(166));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.NotificationSubscriptions' at Center.", repo.CHROME.MainFrame.NotificationSubscriptionsInfo, new RecordItemIndex(167));
            repo.CHROME.MainFrame.NotificationSubscriptions.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.NotificationsSubscriptionsView' at Center.", repo.CHROME.MainFrame.NotificationsSubscriptionsViewInfo, new RecordItemIndex(168));
            repo.CHROME.MainFrame.NotificationsSubscriptionsView.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "58");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.LeftFrame.Settings' at Center.", repo.CHROME.LeftFrame.SettingsInfo, new RecordItemIndex(170));
            repo.CHROME.LeftFrame.Settings.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CHROME.MainFrame.PublicAPI' at Center.", repo.CHROME.MainFrame.PublicAPIInfo, new RecordItemIndex(171));
            repo.CHROME.MainFrame.PublicAPI.Click();
            Delay.Milliseconds(200);
            
            Snap(snapPath, "59");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
