///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SyncFilesWithOnedriveFilesOnDemand
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SyncFilesWithOnedriveFilesOnDemandRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("a60a7d66-fe5e-415b-a7aa-9bd7020ac36b")]
    public partial class SyncFilesWithOnedriveFilesOnDemandRepository : RepoGenBaseFolder
    {
        static SyncFilesWithOnedriveFilesOnDemandRepository instance = new SyncFilesWithOnedriveFilesOnDemandRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SyncFilesWithOnedriveFilesOnDemandRepository element repository.
        /// </summary>
        [RepositoryFolder("a60a7d66-fe5e-415b-a7aa-9bd7020ac36b")]
        public static SyncFilesWithOnedriveFilesOnDemandRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SyncFilesWithOnedriveFilesOnDemandRepository() 
            : base("SyncFilesWithOnedriveFilesOnDemandRepository", "/", null, 0, false, "a60a7d66-fe5e-415b-a7aa-9bd7020ac36b", ".\\RepositoryImages\\SyncFilesWithOnedriveFilesOnDemandRepositorya60a7d66.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a60a7d66-fe5e-415b-a7aa-9bd7020ac36b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class SyncFilesWithOnedriveFilesOnDemandRepositoryFolders
    {
    }
#pragma warning restore 0436
}